version: "3.8"

services:
  jenkins:
    container_name: jenkins-container
    build:
      context: .
      dockerfile: dockerfiles/jenkinsDockerfile/Dockerfile
    image: jenkins-image
    restart: unless-stopped
    user: root
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - /home/groot/jenkins:/var/jenkins_home
      - /home/groot/.ssh:/root/.ssh

  rabbitmq:
    container_name: rabbitmq-container
    build:
      context: .
      dockerfile: dockerfiles/rabbitmqDokerfile/Dockerfile
    image: rabbitmq-image
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    restart: unless-stopped
